{% set name = "tensorboard-data-server" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/7a/13/e503968fefabd4c6b2650af21e110aa8466fe21432cd7c43a84577a89438/tensorboard_data_server-{{ version }}-py3-none-any.whl
  sha256: 7e0610d205889588983836ec05dc098e80f97b7e7bbff7e994ebb78f578d0ddb

build:
  script: "python -m pip install tensorboard_data_server-{{ version }}*.whl --no-deps --ignore-installed -vv "
  number: 1
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - tensorboard_data_server

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_family: Apache
  #  license_file: LICENSE
  summary: 'Data server for TensorBoard'
  dev_url: https://github.com/tensorflow/tensorboard/tree/master/tensorboard/data/server

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
